export const assistanceTypesData = [
  {
    id: 1,
    name: "Financial Aid",
    type: "Monetary",
    unit: "USD",
    status: "true",
    date_of: "2024-10-01",
    update_of: "2025-01-15",
  },
  {
    id: 2,
    name: "Food Basket",
    type: "In-Kind",
    unit: "Package",
    status: "true",
    date_of: "2024-10-05",
    update_of: "2025-01-10",
  },
  {
    id: 3,
    name: "Medical Support",
    type: "Health",
    unit: "Session",
    status: "true",
    date_of: "2024-10-10",
    update_of: "2024-12-20",
  },
  {
    id: 4,
    name: "Educational Scholarship",
    type: "Education",
    unit: "Semester",
    status: "true",
    date_of: "2024-10-15",
    update_of: "2025-01-05",
  },
  {
    id: 5,
    name: "Emergency Relief",
    type: "Emergency",
    unit: "Kit",
    status: "true",
    date_of: "2024-11-01",
    update_of: "2024-12-28",
  },
];